# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
# Build Stage 
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool: 'Default'
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'acrforaksdemo31'
        repository: 'app5/app5nginx'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # List files from Build Artifact Staging Directory - After Copy
    ## bash: echo After copying to Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'    
 
